### ISSUE TITLE
Files without a namespace block are not fixed

### ISSUE THREAD

**Issue by bernhof** [pauer24/VsNamespaceFixer#13]
If a namespace block is not present, the tool doesn't appear to do anything, e.g.:
```
using System;

class MyClass {
    // ...
}
```
Expected behaviour would be to add a namespace block around the class, as such:

```
using System;

namespace MyApp {
    class MyClass {
        // ...
    }
}
```
This is specifically useful when [converting old Web Site projects to Web Applications](https://blogs.msdn.microsoft.com/webdev/2009/10/29/converting-a-web-site-project-to-a-web-application-project/). These project types did not have namespaces in classes by default, which means that a lot of files just float around in the root (ie. empty) namespace. This is the specific reason I decided to try out the extension.

You may decide that this is not the intended use, which is fine. Just wanted to let you know of this possible use case, in which the extension would be *very* helpful (ie. save us from manually adding namespace blocks in hundreds of files).

Cheers.

**Comment by pauer24** [comment]
Definitely is not the intended use case, nevertheless, if you push a PR
with these changes, I'll be glad to review it and add it :)

Regards,
P.

**Comment by bernhof** [comment]
I likely won't find the time for that, unfortunately. We ended up handling this manually. Since this is not the intended use case, I'll close the issue for now.

**Comment by Tr4ncer** [comment]
Hello,
I can maybe look at that.
You have to create the namespace if it does not exist.

@pauer24 What do you think ? I try?

**Comment by pauer24** [comment]
Sure! Be my man! But in my opinion is not very useful: this extension only
works for VS, and when you create a class with VS it creates it with the
namespace block.

Either way, if you feel like you want to try it, feel free!! :D

Cheers!

P.

**Comment by Tr4ncer** [comment]
In VB.NET, there is much less automatism. When creating a class, there is nothing but the name of the class. :disappointed_relieved:

Example :
In a Hello project, Everybody folder:
```
Public Class MyTest
End Class
```
Instead of

```
Namespace Everybody 
  Public Class MyTest
  End Class
End Namespace
```

_Note: remember in VB.Net, there is no need to put the namepace of the project._:mask:

You have the chance to develop in C#. :cupid:

Even with the new [VS2019](https://docs.microsoft.com/fr-fr/visualstudio/ide/reference/sync-namespace-and-folder-name?view=vs-2019), it [will not](https://github.com/dotnet/vblang/issues/351) change [before long](https://github.com/dotnet/roslyn/issues/14341)...

**Comment by pauer24** [comment]
You are right! Didn't notice that... A long time without touching that old
thing called VB.NET...

I feel like is more useful now :) And if you are still interested, I
encourage you to develop it! :D

P.
